from agent.rag.retrieval import Retriever
from agent.tools.sqlite_tool import SQLiteTool
from agent.dspy_modules import DSPyModules

class HybridGraph:
    def __init__(self):
        self.retriever = Retriever()
        self.sqlite = SQLiteTool()
        self.dspy = DSPyModules(self.sqlite)
        self.log = []

    def run(self, query, qid, format_hint):
        self.log.append({"qid": qid, "query": query})
        route = self.dspy.router(query)
        self.log.append({"route": route})
        docs = self.retriever.retrieve(query)
        sql = ""
        rows = None
        citations = []

        
        if route in ('sql','hybrid'):
            plan = self.dspy.planner(query, docs)
            try:
                sql = self.dspy.nl2sql(query, plan)
                rows, cols = self.sqlite.execute(sql)
                citations += self.sqlite.infer_tables_from_sql(sql)
            except Exception as e:
                
                for i in range(2):
                    sql = self.dspy.repair_sql(sql, str(e), i)
                    try:
                        rows, cols = self.sqlite.execute(sql)
                        citations += self.sqlite.infer_tables_from_sql(sql)
                        break
                    except:
                        continue

        
        answer, used_doc_chunks = self.dspy.synthesizer(query, format_hint, rows, docs)
        citations += used_doc_chunks
        citations = list(dict.fromkeys(citations))  

        return {
            "final_answer": answer,
            "sql": sql,
            "confidence": 0.9,
            "explanation": "Generated by HybridGraph",
            "citations": citations
        }
